version: "3"
services:
  node:
    build: .
    command: "npm start"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - app_network  # Definindo uma rede (caso você precise de outras interações entre containers)
    restart: unless-stopped
networks:
  app_network:
    driver: bridge