SELECT 
	R.CODCFO,
	COUNT(1) QTDREGISTROS,
	SUM(R.VLRTOT) VLRTOT,
	SUM(R.BASEICMS) BASEICMS,
	SUM(R.VLRICMS) VLRICMS,
	SUM(R.BASEICMSST) BASEICMSST,
	SUM(R.VLRICMSST) VLRICMSST,	
	SUM(R.BASEIPI) BASEIPI,
	SUM(R.VLRIPI) VLRIPI,
	SUM(R.BASEPIS) BASEPIS,
	SUM(R.VLRPIS) VLRPIS,
	SUM(R.BASECOFINS) BASECOFINS,
	SUM(R.VLRCOFINS) VLRCOFINS,
	SUM(R.BASEISS) BASEISS,
	SUM(R.VLRISS) VLRISS,
	SUM(R.BASEINSS) BASEINSS,
	SUM(R.VLRINSS) VLRINSS,
	SUM(R.VLRFCP) VLRFCP,
	SUM(R.VLRFCPINT) VLRFCPINT,
	SUM(R.VLRDIFALREM) VLRDIFALREM,
	SUM(R.VLRDIFALDEST) VLRDIFALDEST,
	SUM(R.VLRICMSPARADIFAL) VLRICMSPARADIFAL,
	SUM(R.BASECSSL) BASECSSL,
	SUM(R.VLRCSSL) VLRCSSL,
	SUM(R.BASEIRF) BASEIRF,
	SUM(R.VLRIRF) VLRIRF,
	SUM(R.BASEIRPJ) BASEIRPJ,
	SUM(R.VLRIRPJ) VLRIRPJ,
	SUM(R.BASECPP) BASECPP,
	SUM(R.VLRCPP) VLRCPP
FROM 
(SELECT
	ITE.CODCFO,
	ITE.VLRTOT,
	COALESCE((SELECT COALESCE(SUM(DIN.BASERED),0) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.CODIMP = 1 AND DIN.SEQUENCIA > 0) + (SELECT COALESCE(SUM(IMP.BASE),0) FROM TGFIMN IMP WHERE IMP.NUNOTA = ITE.NUNOTA AND IMP.SEQUENCIA = ITE.SEQUENCIA AND IMP.TIPOIMPOSTO = 1),0) BASEICMS,
	COALESCE((SELECT COALESCE(SUM(DIN.VALOR),0) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.CODIMP = 1 AND DIN.SEQUENCIA > 0) + (SELECT COALESCE(SUM(IMP.VALOR),0) FROM TGFIMN IMP WHERE IMP.NUNOTA = ITE.NUNOTA AND IMP.SEQUENCIA = ITE.SEQUENCIA AND IMP.TIPOIMPOSTO = 1),0) VLRICMS,
	
    COALESCE((SELECT COALESCE(SUM(DIN.BASERED),0) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.CODIMP = 2 AND DIN.SEQUENCIA > 0) + (SELECT COALESCE(SUM(IMP.BASE),0) FROM TGFIMN IMP WHERE IMP.NUNOTA = ITE.NUNOTA AND IMP.SEQUENCIA = ITE.SEQUENCIA AND IMP.TIPOIMPOSTO = 2),0) BASEICMSST,
	COALESCE((SELECT COALESCE(SUM(DIN.VALOR),0) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.CODIMP = 2 AND DIN.SEQUENCIA > 0) + (SELECT COALESCE(SUM(IMP.VALOR),0) FROM TGFIMN IMP WHERE IMP.NUNOTA = ITE.NUNOTA AND IMP.SEQUENCIA = ITE.SEQUENCIA AND IMP.TIPOIMPOSTO = 2),0) VLRICMSST,
	
    COALESCE((SELECT COALESCE(SUM(DIN.BASERED),0) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.CODIMP = 3 AND DIN.SEQUENCIA > 0) + (SELECT COALESCE(SUM(IMP.BASE),0) FROM TGFIMN IMP WHERE IMP.NUNOTA = ITE.NUNOTA AND IMP.SEQUENCIA = ITE.SEQUENCIA AND IMP.TIPOIMPOSTO = 3),0) BASEIPI,
	COALESCE((SELECT COALESCE(SUM(DIN.VALOR),0) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.CODIMP = 3 AND DIN.SEQUENCIA > 0) + (SELECT COALESCE(SUM(IMP.VALOR),0) FROM TGFIMN IMP WHERE IMP.NUNOTA = ITE.NUNOTA AND IMP.SEQUENCIA = ITE.SEQUENCIA AND IMP.TIPOIMPOSTO = 3),0) VLRIPI,
	
    COALESCE((SELECT COALESCE(SUM(DIN.BASERED),0) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.CODIMP = 4 AND DIN.SEQUENCIA > 0) + (SELECT COALESCE(SUM(IMP.BASE),0) FROM TGFIMN IMP WHERE IMP.NUNOTA = ITE.NUNOTA AND IMP.SEQUENCIA = ITE.SEQUENCIA AND IMP.TIPOIMPOSTO = 4),0) BASEISS,
	COALESCE((SELECT COALESCE(SUM(DIN.VALOR),0) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.CODIMP = 4 AND DIN.SEQUENCIA > 0) + (SELECT COALESCE(SUM(IMP.VALOR),0) FROM TGFIMN IMP WHERE IMP.NUNOTA = ITE.NUNOTA AND IMP.SEQUENCIA = ITE.SEQUENCIA AND IMP.TIPOIMPOSTO = 4),0) VLRISS,
	
    COALESCE((SELECT COALESCE(SUM(DIN.BASERED),0) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.CODIMP = 5 AND DIN.SEQUENCIA > 0) + (SELECT COALESCE(SUM(IMP.BASE),0) FROM TGFIMN IMP WHERE IMP.NUNOTA = ITE.NUNOTA AND IMP.SEQUENCIA = ITE.SEQUENCIA AND IMP.TIPOIMPOSTO = 5),0) BASEINSS,
	COALESCE((SELECT COALESCE(SUM(DIN.VALOR),0) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.CODIMP = 5 AND DIN.SEQUENCIA > 0) + (SELECT COALESCE(SUM(IMP.VALOR),0) FROM TGFIMN IMP WHERE IMP.NUNOTA = ITE.NUNOTA AND IMP.SEQUENCIA = ITE.SEQUENCIA AND IMP.TIPOIMPOSTO = 5),0) VLRINSS,
	
    COALESCE(
    CASE 
        WHEN (SELECT COALESCE(SUM(DIN.BASERED), 0) 
              FROM TGFDIN DIN 
              WHERE DIN.NUNOTA = ITE.NUNOTA 
                AND DIN.SEQUENCIA = ITE.SEQUENCIA 
                AND DIN.CODIMP = 6 
                AND DIN.SEQUENCIA > 0) > 0 
        THEN (SELECT COALESCE(SUM(DIN.BASERED), 0) 
              FROM TGFDIN DIN 
              WHERE DIN.NUNOTA = ITE.NUNOTA 
                AND DIN.SEQUENCIA = ITE.SEQUENCIA 
                AND DIN.CODIMP = 6 
                AND DIN.SEQUENCIA > 0)
        ELSE (SELECT COALESCE(SUM(DIN.BASERED), 0) 
              FROM TGFDIN DIN 
              WHERE DIN.NUNOTA = ITE.NUNOTA 
                AND DIN.SEQUENCIA = ITE.SEQUENCIA 
                AND DIN.CODIMP = 6 
                AND DIN.SEQUENCIA > 0) + 
             (SELECT COALESCE(SUM(IMP.BASE), 0) 
              FROM TGFIMN IMP 
              WHERE IMP.NUNOTA = ITE.NUNOTA 
                AND IMP.SEQUENCIA = ITE.SEQUENCIA 
                AND IMP.TIPOIMPOSTO = 6)
    END, 0) AS BASEPIS,
	COALESCE((SELECT COALESCE(SUM(DIN.VALOR),0) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.CODIMP = 6 AND DIN.SEQUENCIA > 0) + (SELECT COALESCE(SUM(IMP.VALOR),0)FROM TGFIMN IMP WHERE IMP.NUNOTA = ITE.NUNOTA AND IMP.SEQUENCIA = ITE.SEQUENCIA AND IMP.TIPOIMPOSTO = 6),0) VLRPIS,
	
    COALESCE(
    CASE 
        WHEN (SELECT COALESCE(SUM(DIN.BASERED), 0) 
              FROM TGFDIN DIN 
              WHERE DIN.NUNOTA = ITE.NUNOTA 
                AND DIN.SEQUENCIA = ITE.SEQUENCIA 
                AND DIN.CODIMP = 7 
                AND DIN.SEQUENCIA > 0) > 0 
        THEN (SELECT COALESCE(SUM(DIN.BASERED), 0) 
              FROM TGFDIN DIN 
              WHERE DIN.NUNOTA = ITE.NUNOTA 
                AND DIN.SEQUENCIA = ITE.SEQUENCIA 
                AND DIN.CODIMP = 7 
                AND DIN.SEQUENCIA > 0)
        ELSE (SELECT COALESCE(SUM(DIN.BASERED), 0) 
              FROM TGFDIN DIN 
              WHERE DIN.NUNOTA = ITE.NUNOTA 
                AND DIN.SEQUENCIA = ITE.SEQUENCIA 
                AND DIN.CODIMP = 7 
                AND DIN.SEQUENCIA > 0) + 
             (SELECT COALESCE(SUM(IMP.BASE), 0) 
              FROM TGFIMN IMP 
              WHERE IMP.NUNOTA = ITE.NUNOTA 
                AND IMP.SEQUENCIA = ITE.SEQUENCIA 
                AND IMP.TIPOIMPOSTO = 7)
    END, 0) AS BASECOFINS,

	COALESCE((SELECT COALESCE(SUM(DIN.VALOR),0) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.CODIMP = 7 AND DIN.SEQUENCIA > 0) + (SELECT COALESCE(SUM(IMP.VALOR),0) FROM TGFIMN IMP WHERE IMP.NUNOTA = ITE.NUNOTA AND IMP.SEQUENCIA = ITE.SEQUENCIA AND IMP.TIPOIMPOSTO = 7),0) VLRCOFINS,
 	
    COALESCE((SELECT COALESCE(SUM(DIN.BASERED),0) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.CODIMP = 8 AND DIN.SEQUENCIA > 0) + (SELECT COALESCE(SUM(IMP.BASE),0) FROM TGFIMN IMP WHERE IMP.NUNOTA = ITE.NUNOTA AND IMP.SEQUENCIA = ITE.SEQUENCIA AND IMP.TIPOIMPOSTO = 8),0) BASEIRF,
	COALESCE((SELECT COALESCE(SUM(DIN.VALOR),0) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.CODIMP = 8 AND DIN.SEQUENCIA > 0) + (SELECT COALESCE(SUM(IMP.VALOR),0) FROM TGFIMN IMP WHERE IMP.NUNOTA = ITE.NUNOTA AND IMP.SEQUENCIA = ITE.SEQUENCIA AND IMP.TIPOIMPOSTO = 8),0) VLRIRF,
	
       COALESCE(
    CASE 
        WHEN (SELECT COALESCE(SUM(DIN.BASERED), 0) 
              FROM TGFDIN DIN 
              WHERE DIN.NUNOTA = ITE.NUNOTA 
                AND DIN.SEQUENCIA = ITE.SEQUENCIA 
                AND DIN.CODIMP = 9
                AND DIN.SEQUENCIA > 0) > 0 
        THEN (SELECT COALESCE(SUM(DIN.BASERED), 0) 
              FROM TGFDIN DIN 
              WHERE DIN.NUNOTA = ITE.NUNOTA 
                AND DIN.SEQUENCIA = ITE.SEQUENCIA 
                AND DIN.CODIMP = 9
                AND DIN.SEQUENCIA > 0)
        ELSE (SELECT COALESCE(SUM(DIN.BASERED), 0) 
              FROM TGFDIN DIN 
              WHERE DIN.NUNOTA = ITE.NUNOTA 
                AND DIN.SEQUENCIA = ITE.SEQUENCIA 
                AND DIN.CODIMP = 9 
                AND DIN.SEQUENCIA > 0) + 
             (SELECT COALESCE(SUM(IMP.BASE), 0) 
              FROM TGFIMN IMP 
              WHERE IMP.NUNOTA = ITE.NUNOTA 
                AND IMP.SEQUENCIA = ITE.SEQUENCIA 
                AND IMP.TIPOIMPOSTO = 9)
    END, 0) AS BASECSSL,
    /* COALESCE((SELECT COALESCE(SUM(DIN.BASERED),0) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.CODIMP = 9 AND DIN.SEQUENCIA > 0) + (SELECT COALESCE(SUM(IMP.BASE),0) FROM TGFIMN IMP WHERE IMP.NUNOTA = ITE.NUNOTA AND IMP.SEQUENCIA = ITE.SEQUENCIA AND IMP.TIPOIMPOSTO = 9),0) BASECSSL, */
	COALESCE((SELECT COALESCE(SUM(DIN.VALOR),0) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.CODIMP = 9 AND DIN.SEQUENCIA > 0) + (SELECT COALESCE(SUM(IMP.VALOR),0) FROM TGFIMN IMP WHERE IMP.NUNOTA = ITE.NUNOTA AND IMP.SEQUENCIA = ITE.SEQUENCIA AND IMP.TIPOIMPOSTO = 9),0) VLRCSSL,
	
    COALESCE((SELECT COALESCE(SUM(DIN.BASERED),0) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.CODIMP = 10 AND DIN.SEQUENCIA > 0) + (SELECT COALESCE(SUM(IMP.BASE),0) FROM TGFIMN IMP WHERE IMP.NUNOTA = ITE.NUNOTA AND IMP.SEQUENCIA = ITE.SEQUENCIA AND IMP.TIPOIMPOSTO = 10),0) BASEIRPJ,
	COALESCE((SELECT COALESCE(SUM(DIN.VALOR),0) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.CODIMP = 10 AND DIN.SEQUENCIA > 0) + (SELECT COALESCE(SUM(IMP.VALOR),0)FROM TGFIMN IMP WHERE IMP.NUNOTA = ITE.NUNOTA AND IMP.SEQUENCIA = ITE.SEQUENCIA AND IMP.TIPOIMPOSTO = 10),0) VLRIRPJ,
	
    COALESCE((SELECT COALESCE(SUM(DIN.BASERED),0) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.CODIMP = 11 AND DIN.SEQUENCIA > 0) + (SELECT COALESCE(SUM(IMP.BASE),0) FROM TGFIMN IMP WHERE IMP.NUNOTA = ITE.NUNOTA AND IMP.SEQUENCIA = ITE.SEQUENCIA AND IMP.TIPOIMPOSTO = 11),0) BASECPP,
	COALESCE((SELECT COALESCE(SUM(DIN.VALOR),0) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.CODIMP = 11 AND DIN.SEQUENCIA > 0) + (SELECT COALESCE(SUM(IMP.VALOR),0) FROM TGFIMN IMP WHERE IMP.NUNOTA = ITE.NUNOTA AND IMP.SEQUENCIA = ITE.SEQUENCIA AND IMP.TIPOIMPOSTO = 11),0) VLRCPP,
	


    COALESCE((SELECT SUM(DIN.VLRFCP) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.SEQUENCIA > 0),0) VLRFCP,
	COALESCE((SELECT SUM(DIN.VLRFCPINT) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.SEQUENCIA > 0),0) VLRFCPINT,
    COALESCE((SELECT SUM(DIN.VLRDIFALREM) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.SEQUENCIA > 0),0) VLRDIFALREM,
	COALESCE((SELECT SUM(DIN.VLRDIFALDEST) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.SEQUENCIA > 0),0) VLRDIFALDEST,
	COALESCE((SELECT SUM(DIN.VLRICMSPARADIFAL) FROM TGFDIN DIN WHERE DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA AND DIN.SEQUENCIA > 0),0) VLRICMSPARADIFAL
FROM TGFITE ITE
INNER JOIN TGFCAB CAB ON(CAB.NUNOTA = ITE.NUNOTA)
INNER JOIN TGFPRO PRO ON(PRO.CODPROD = ITE.CODPROD)
INNER JOIN TSIEMP EMP ON(EMP.CODEMP = ITE.CODEMP)
INNER JOIN TGFPAR PAR ON(PAR.CODPARC = CAB.CODPARC)
WHERE ((CASE :P_TIPDATA 
            WHEN '1' THEN CAB.DTNEG 
            WHEN '2' THEN CAB.DTMOV
            WHEN '3' THEN CAB.DTENTSAI
            WHEN '4' THEN CAB.DTFATUR
        END) BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN)
  AND (CAB.NUMNOTA = :P_NUMNOTA OR :P_NUMNOTA IS NULL)
  AND (CAB.NUNOTA = :P_NUNOTA OR :P_NUNOTA IS NULL)
  AND (EMP.CODEMPMATRIZ = :P_CODEMPMATRIZ OR :P_CODEMPMATRIZ = 9999)
  AND (CAB.CODEMP = :P_CODEMP OR :P_CODEMP IS NULL)
  AND (CAB.CODPARC = :P_CODPARC OR :P_CODPARC IS NULL)
  AND (CAB.ORDEMCARGA = :P_ORDEMCARGA OR :P_ORDEMCARGA IS NULL)
  AND (CAB.TIPMOV = :P_TIPMOV OR :P_TIPMOV = 'ALL')
  AND (CAB.STATUSNFE = :P_STATUSNFE OR :P_STATUSNFE = 'ALL')
  AND (CAB.STATUSNFSE = :P_STATUSNFSE OR :P_STATUSNFSE = 'ALL')
  AND (CAB.STATUSCTE = :P_STATUSCTE OR :P_STATUSCTE = 'ALL')
  AND (CAB.CODTIPOPER = :P_CODTIPOPER OR :P_CODTIPOPER IS NULL)
  AND (ITE.CODPROD = :P_CODPROD OR :P_CODPROD IS NULL)
  AND (CAB.CHAVENFE = :P_CHAVENFE OR :P_CHAVENFE IS NULL)
  AND (CAB.CHAVENFSE = :P_CHAVENFSE OR :P_CHAVENFSE IS NULL)
  AND (CAB.CHAVECTE = :P_CHAVECTE OR :P_CHAVECTE IS NULL)  
  AND (CAB.STATUSNOTA = :P_STATUSNOTA OR :P_STATUSNOTA = 'ALL')
  AND (ITE.USOPROD = :P_USOPROD OR :P_USOPROD = 'ALL')
  AND (PRO.CODGRUPOPROD = :P_CODGRUPOPROD OR :P_CODGRUPOPROD IS NULL)
  AND (PRO.CODMARCA = :P_CODMARCA OR :P_CODMARCA IS NULL)
  AND (ITE.CODTRIB = :P_CODTRIB OR :P_CODTRIB = 999)
  AND (ITE.CSTIPI = :P_CSTIPI OR :P_CSTIPI = 999)
  AND (ITE.CODCFO = :P_CODCFO OR :P_CODCFO IS NULL)
  AND (CAB.CODUFORIGEM = :P_CODUFORIGEM OR :P_CODUFORIGEM IS NULL)
  AND (CAB.CODUFDESTINO = :P_CODUFDESTINO OR :P_CODUFDESTINO IS NULL)
  AND (PRO.NCM = :P_NCM OR :P_NCM IS NULL)
  AND (PAR.CLASSIFICMS = :P_CLASSIFICMS OR :P_CLASSIFICMS = 'ALL')


AND (CAB.CODTIPOPER NOT IN (SELECT CODTIPOPER FROM AD_TOPNECONFIMP))

)R
WHERE COALESCE((R.VLRICMS),0) > (CASE WHEN :P_LCTSCOMIMPOSTO = '1' THEN 0 ELSE -1 END)
  AND COALESCE((R.VLRICMSST),0) > (CASE WHEN :P_LCTSCOMIMPOSTO = '2' THEN 0 ELSE -1 END)
  AND COALESCE((R.VLRIPI),0) > (CASE WHEN :P_LCTSCOMIMPOSTO = '3' THEN 0 ELSE -1 END)
  AND COALESCE((R.VLRISS),0) > (CASE WHEN :P_LCTSCOMIMPOSTO = '4' THEN 0 ELSE -1 END)   	
  AND COALESCE((R.VLRINSS),0) > (CASE WHEN :P_LCTSCOMIMPOSTO = '5' THEN 0 ELSE -1 END)
  AND COALESCE((R.VLRPIS),0) > (CASE WHEN :P_LCTSCOMIMPOSTO = '6' THEN 0 ELSE -1 END)
  AND COALESCE((R.VLRCOFINS),0) > (CASE WHEN :P_LCTSCOMIMPOSTO = '7' THEN 0 ELSE -1 END)
  AND COALESCE((R.VLRIRF),0) > (CASE WHEN :P_LCTSCOMIMPOSTO = '8' THEN 0 ELSE -1 END)
  AND COALESCE((R.VLRCSSL),0) > (CASE WHEN :P_LCTSCOMIMPOSTO = '9' THEN 0 ELSE -1 END)
  AND COALESCE((R.VLRIRPJ),0) > (CASE WHEN :P_LCTSCOMIMPOSTO = '10' THEN 0 ELSE -1 END)
  AND COALESCE((R.VLRCPP),0) > (CASE WHEN :P_LCTSCOMIMPOSTO = '11' THEN 0 ELSE -1 END)
  AND COALESCE((R.VLRFCP),0) > (CASE WHEN :P_LCTSCOMIMPOSTO = '92' THEN 0 ELSE -1 END)
  AND COALESCE((R.VLRFCPINT),0) > (CASE WHEN :P_LCTSCOMIMPOSTO = '93' THEN 0 ELSE -1 END)
  AND COALESCE((R.VLRDIFALREM),0) > (CASE WHEN :P_LCTSCOMIMPOSTO = '94' THEN 0 ELSE -1 END)
  AND COALESCE((R.VLRDIFALDEST),0) > (CASE WHEN :P_LCTSCOMIMPOSTO = '95' THEN 0 ELSE -1 END)
  AND COALESCE((R.VLRICMSPARADIFAL),0) > (CASE WHEN :P_LCTSCOMIMPOSTO = '96' THEN 0 ELSE -1 END) 
GROUP BY R.CODCFO
ORDER BY 1;